### ISSUE TITLE
在 Firefox 的 BBSFox 使用懷源黑體時，行高過大

### ISSUE THREAD

**Issue by akiratw** [akiratw/kaigen-gothic#3]
在 Firefox 的 [BBSFox](https://addons.mozilla.org/zh-TW/firefox/addon/bbsfox/) 或瀏覽 [PTT 網頁版](https://www.ptt.cc)使用懷源黑體時，行高太大導致上一行被覆蓋。如圖：

![BBSF](https://cloud.githubusercontent.com/assets/1629018/7665740/255a9ed4-fbf8-11e4-9c2b-52aaf0632ee3.png)

**Comment by ryuanlu** [comment]
可以修改 hhea ascender、descender 的值。1.004 的行高為 1.48 倍。
